import type { Language } from '../types'

export type CopyStrings = (typeof copy)[Language]

export const copy = {
  vi: {
    title: 'Bảng ghi điểm',
    subtitle: 'Theo dõi điểm từng ván, sắp xếp hạng realtime và sửa nhanh ván vừa nhập.',
    setupHeading: 'Thiết lập phòng',
    startingScore: 'Điểm khởi tạo',
    winningScore: 'Điểm chiến thắng (tùy chọn)',
    winningScorePlaceholder: 'Ví dụ: 100',
    players: 'Người chơi',
    playerPlaceholder: (index: number) => `Người chơi ${index + 1}`,
    duplicateNameError: 'Tên người chơi không được trùng nhau.',
    emptyNameError: 'Vui lòng nhập tên cho tất cả người chơi.',
    minPlayersError: 'Cần ít nhất 2 người chơi.',
    addPlayer: '+ Thêm người',
    removePlayer: '- Bớt người',
    startGame: 'Bắt đầu phòng chơi',
    endMatch: 'Kết thúc trận',
    autoWinTitle: '🎉 Đã có người chạm mốc chiến thắng!',
    victoryBadge: 'Chiến thắng',
    victoryTitle: 'Chúc mừng chiến thắng!',
    victoryMessageSingle: (name: string, score: number) =>
      `${name} đã đạt mốc ${score} điểm và giành chiến thắng!`,
    victoryMessageMulti: (count: number, names: string, score: number) =>
      `${count} người chơi đã chạm mốc ${score} điểm: ${names}`,
    victoryTargetLabel: 'Mốc chiến thắng',
    victoryContinue: 'Xem kết quả',
    summaryTitle: 'Kết quả tổng kết',
    backToMatch: 'Quay lại trận đấu',
    totalRounds: 'Tổng số ván',
    wld: 'Thắng/Thua/Hòa',
    highestLowest: 'Ván cao nhất: {highest} | Ván thấp nhất: {lowest}',
    copyResult: 'Copy kết quả text',
    newRoom: 'Tạo phòng mới',
    shareTextLabel: 'Bản sao để chia sẻ',
    scoreInputHeading: 'Nhập điểm từng ván',
    rankingHeading: 'Bảng xếp hạng',
    saveRound: 'Lưu ván mới',
    editLastRound: 'Sửa ván cuối',
    endGame: 'Kết thúc game',
    deleteLastRound: 'Xóa ván cuối',
    playedRounds: (count: number) => `Đã chơi ${count} ván.`,
    copied: 'Đã copy kết quả.',
    copyFailed: 'Không copy được. Hãy copy thủ công từ khung text bên dưới.',
    winnerSingle: (name: string, score: number) => `🎉 ${name} đã đạt mốc chiến thắng ${score} điểm!`,
    winnerMulti: (count: number, names: string, score: number) =>
      `🏆 Đã có ${count} người đạt mốc ${score} điểm: ${names}`,
    rankLabel: (index: number) => `Hạng ${index + 1}`,
    shareTitle: 'SCOREKEEPER - KẾT QUẢ CHUNG CUỘC',
    sharePlayerCount: (count: number) => `Số người chơi: ${count}`,
    shareRoundCount: (count: number) => `Số ván: ${count}`,
    shareWinScore: (score: number | null) =>
      score !== null ? `Điểm chiến thắng: ${score}` : 'Điểm chiến thắng: Không đặt',
    shareRanking: 'XẾP HẠNG:',
    shareLine: (
      rank: string,
      name: string,
      score: number,
      w: number,
      l: number,
      d: number,
      hi: number,
      lo: number,
    ) =>
      `${rank} - ${name}: ${score} điểm | Thắng/Thua/Hòa ${w}/${l}/${d} | Cao nhất ${hi}, Thấp nhất ${lo}`,
  },
  en: {
    title: 'Scoreboard',
    subtitle: 'Track round scores, view live rankings, and quickly fix the latest round.',
    setupHeading: 'Room Setup',
    startingScore: 'Starting score',
    winningScore: 'Winning score (optional)',
    winningScorePlaceholder: 'Example: 100',
    players: 'Players',
    playerPlaceholder: (index: number) => `Player ${index + 1}`,
    duplicateNameError: 'Player names must be unique.',
    emptyNameError: 'Please enter all player names.',
    minPlayersError: 'At least 2 players are required.',
    addPlayer: '+ Add player',
    removePlayer: '- Remove player',
    startGame: 'Start game room',
    endMatch: 'Match finished',
    autoWinTitle: '🎉 Someone reached the winning score!',
    victoryBadge: 'Victory',
    victoryTitle: 'Congratulations!',
    victoryMessageSingle: (name: string, score: number) =>
      `${name} reached ${score} points and won the game!`,
    victoryMessageMulti: (count: number, names: string, score: number) =>
      `${count} players reached ${score} points: ${names}`,
    victoryTargetLabel: 'Winning score',
    victoryContinue: 'View results',
    summaryTitle: 'Game summary',
    backToMatch: 'Back to match',
    totalRounds: 'Total rounds',
    wld: 'Win/Loss/Draw',
    highestLowest: 'Highest round: {highest} | Lowest round: {lowest}',
    copyResult: 'Copy result text',
    newRoom: 'Create new room',
    shareTextLabel: 'Share-ready text',
    scoreInputHeading: 'Enter round scores',
    rankingHeading: 'Leaderboard',
    saveRound: 'Save new round',
    editLastRound: 'Edit last round',
    endGame: 'End game',
    deleteLastRound: 'Delete last round',
    playedRounds: (count: number) => `${count} rounds played.`,
    copied: 'Result copied.',
    copyFailed: 'Could not copy. Please copy manually from the text area below.',
    winnerSingle: (name: string, score: number) => `🎉 ${name} reached the winning score of ${score}!`,
    winnerMulti: (count: number, names: string, score: number) =>
      `🏆 ${count} players reached the winning score of ${score}: ${names}`,
    rankLabel: (index: number) => `Rank ${index + 1}`,
    shareTitle: 'SCOREKEEPER - FINAL RESULTS',
    sharePlayerCount: (count: number) => `Players: ${count}`,
    shareRoundCount: (count: number) => `Rounds: ${count}`,
    shareWinScore: (score: number | null) =>
      score !== null ? `Winning score: ${score}` : 'Winning score: Not set',
    shareRanking: 'RANKING:',
    shareLine: (
      rank: string,
      name: string,
      score: number,
      w: number,
      l: number,
      d: number,
      hi: number,
      lo: number,
    ) =>
      `${rank} - ${name}: ${score} pts | W/L/D ${w}/${l}/${d} | Highest ${hi}, Lowest ${lo}`,
  },
} as const

export function getCopy(language: Language): CopyStrings {
  return copy[language]
}
